#!/bin/bash --login

OUTPATH=/mnt/scratch/zhangf37/PROJECT/20190813_MSUPRP/06.HISAT2/144sample_stranded_PE125

hisat2 \
  --summary-file ${OUTPATH}/${SAMPLE}.summary.txt \
  -p 4 \
  -x /mnt/home/zhangf37/Genomic/Sus_scrofa/ensembl_release97/snp_ss_exon/sus_scrofa.97 \
  -1 ${FILENAME1} \
  -2 ${FILENAME2} \
  -S ${OUTPATH}/${SAMPLE}.sam \
  --rna-strandness RF \
  --dta \
  --no-unal \
  > ${SAMPLE}.log 2>&1

scontrol show job $SLURM_JOB_ID > ${SAMPLE}.job.log
